//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/PlayerActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActionMap"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""2d1f9f5e-90a2-4be9-b7d0-14365c5c0a5d"",
            ""actions"": [
                {
                    ""name"": ""ControllerButtonsShoot"",
                    ""type"": ""Button"",
                    ""id"": ""cd86d078-7ea8-4e02-8904-1aa3ec99a4d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsPotion"",
                    ""type"": ""Button"",
                    ""id"": ""85a17828-d879-49ba-a1ee-194e2162b8e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsKey"",
                    ""type"": ""Button"",
                    ""id"": ""34d8c5a2-8f5a-465a-8240-0e17943f2dde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cca577e8-998e-490d-a9a9-4a538a51c64d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0967b852-e45e-4de8-acca-0aca0fb24033"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a6e1681-3328-4f7a-8dc4-8635f81fb7f1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsPotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35649c32-5081-40cf-a76d-e997415c9438"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsPotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee83604f-f5b2-4595-beb6-d39258dac704"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b07c49ae-c2c0-4a98-91b7-f808c59101a1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsShoot = m_PlayerMovement.FindAction("ControllerButtonsShoot", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsPotion = m_PlayerMovement.FindAction("ControllerButtonsPotion", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsKey = m_PlayerMovement.FindAction("ControllerButtonsKey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private IPlayerMovementActions m_PlayerMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerMovement_ControllerButtonsShoot;
    private readonly InputAction m_PlayerMovement_ControllerButtonsPotion;
    private readonly InputAction m_PlayerMovement_ControllerButtonsKey;
    public struct PlayerMovementActions
    {
        private @PlayerActionMap m_Wrapper;
        public PlayerMovementActions(@PlayerActionMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @ControllerButtonsShoot => m_Wrapper.m_PlayerMovement_ControllerButtonsShoot;
        public InputAction @ControllerButtonsPotion => m_Wrapper.m_PlayerMovement_ControllerButtonsPotion;
        public InputAction @ControllerButtonsKey => m_Wrapper.m_PlayerMovement_ControllerButtonsKey;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterface != null)
            {
                @ControllerButtonsShoot.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsShoot.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsShoot.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsPotion.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsPotion.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsPotion.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsKey.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
                @ControllerButtonsKey.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
                @ControllerButtonsKey.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
            }
            m_Wrapper.m_PlayerMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ControllerButtonsShoot.started += instance.OnControllerButtonsShoot;
                @ControllerButtonsShoot.performed += instance.OnControllerButtonsShoot;
                @ControllerButtonsShoot.canceled += instance.OnControllerButtonsShoot;
                @ControllerButtonsPotion.started += instance.OnControllerButtonsPotion;
                @ControllerButtonsPotion.performed += instance.OnControllerButtonsPotion;
                @ControllerButtonsPotion.canceled += instance.OnControllerButtonsPotion;
                @ControllerButtonsKey.started += instance.OnControllerButtonsKey;
                @ControllerButtonsKey.performed += instance.OnControllerButtonsKey;
                @ControllerButtonsKey.canceled += instance.OnControllerButtonsKey;
            }
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);
    public interface IPlayerMovementActions
    {
        void OnControllerButtonsShoot(InputAction.CallbackContext context);
        void OnControllerButtonsPotion(InputAction.CallbackContext context);
        void OnControllerButtonsKey(InputAction.CallbackContext context);
    }
}
