//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/PlayerActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionMap : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActionMap"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""2d1f9f5e-90a2-4be9-b7d0-14365c5c0a5d"",
            ""actions"": [
                {
                    ""name"": ""ControllerButtonsShoot"",
                    ""type"": ""Button"",
                    ""id"": ""cd86d078-7ea8-4e02-8904-1aa3ec99a4d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsPotion"",
                    ""type"": ""Button"",
                    ""id"": ""85a17828-d879-49ba-a1ee-194e2162b8e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsKey"",
                    ""type"": ""Button"",
                    ""id"": ""34d8c5a2-8f5a-465a-8240-0e17943f2dde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsClassScroll"",
                    ""type"": ""Button"",
                    ""id"": ""29796ca6-b99f-4060-b6c1-ba77631304a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerButtonsClassSelect"",
                    ""type"": ""Button"",
                    ""id"": ""b225f838-91a9-4316-87bf-01aa018e197f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cca577e8-998e-490d-a9a9-4a538a51c64d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0967b852-e45e-4de8-acca-0aca0fb24033"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a6e1681-3328-4f7a-8dc4-8635f81fb7f1"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsPotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35649c32-5081-40cf-a76d-e997415c9438"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsPotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee83604f-f5b2-4595-beb6-d39258dac704"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b07c49ae-c2c0-4a98-91b7-f808c59101a1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5752f55a-8357-47f5-9549-295e178f4db0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f59839f9-9dac-440c-b705-356a15d040c9"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2583d456-1823-4c70-83e3-358ba33b072c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e1f3210d-9825-4c48-9316-1b1c70df4c37"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""867e025b-07e2-410b-a17b-f97a0b90b532"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""db6b7004-7c9c-4f71-a700-eacbc7a0c451"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""969e3e20-c502-4a83-885f-1b14407d0c79"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0165ffca-8bc6-43a5-987e-97befa919bdc"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerButtonsClassSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsShoot = m_PlayerMovement.FindAction("ControllerButtonsShoot", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsPotion = m_PlayerMovement.FindAction("ControllerButtonsPotion", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsKey = m_PlayerMovement.FindAction("ControllerButtonsKey", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsClassScroll = m_PlayerMovement.FindAction("ControllerButtonsClassScroll", throwIfNotFound: true);
        m_PlayerMovement_ControllerButtonsClassSelect = m_PlayerMovement.FindAction("ControllerButtonsClassSelect", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private IPlayerMovementActions m_PlayerMovementActionsCallbackInterface;
    private readonly InputAction m_PlayerMovement_ControllerButtonsShoot;
    private readonly InputAction m_PlayerMovement_ControllerButtonsPotion;
    private readonly InputAction m_PlayerMovement_ControllerButtonsKey;
    private readonly InputAction m_PlayerMovement_ControllerButtonsClassScroll;
    private readonly InputAction m_PlayerMovement_ControllerButtonsClassSelect;
    public struct PlayerMovementActions
    {
        private @PlayerActionMap m_Wrapper;
        public PlayerMovementActions(@PlayerActionMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @ControllerButtonsShoot => m_Wrapper.m_PlayerMovement_ControllerButtonsShoot;
        public InputAction @ControllerButtonsPotion => m_Wrapper.m_PlayerMovement_ControllerButtonsPotion;
        public InputAction @ControllerButtonsKey => m_Wrapper.m_PlayerMovement_ControllerButtonsKey;
        public InputAction @ControllerButtonsClassScroll => m_Wrapper.m_PlayerMovement_ControllerButtonsClassScroll;
        public InputAction @ControllerButtonsClassSelect => m_Wrapper.m_PlayerMovement_ControllerButtonsClassSelect;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterface != null)
            {
                @ControllerButtonsShoot.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsShoot.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsShoot.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsShoot;
                @ControllerButtonsPotion.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsPotion.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsPotion.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsPotion;
                @ControllerButtonsKey.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
                @ControllerButtonsKey.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
                @ControllerButtonsKey.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsKey;
                @ControllerButtonsClassScroll.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassScroll;
                @ControllerButtonsClassScroll.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassScroll;
                @ControllerButtonsClassScroll.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassScroll;
                @ControllerButtonsClassSelect.started -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassSelect;
                @ControllerButtonsClassSelect.performed -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassSelect;
                @ControllerButtonsClassSelect.canceled -= m_Wrapper.m_PlayerMovementActionsCallbackInterface.OnControllerButtonsClassSelect;
            }
            m_Wrapper.m_PlayerMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ControllerButtonsShoot.started += instance.OnControllerButtonsShoot;
                @ControllerButtonsShoot.performed += instance.OnControllerButtonsShoot;
                @ControllerButtonsShoot.canceled += instance.OnControllerButtonsShoot;
                @ControllerButtonsPotion.started += instance.OnControllerButtonsPotion;
                @ControllerButtonsPotion.performed += instance.OnControllerButtonsPotion;
                @ControllerButtonsPotion.canceled += instance.OnControllerButtonsPotion;
                @ControllerButtonsKey.started += instance.OnControllerButtonsKey;
                @ControllerButtonsKey.performed += instance.OnControllerButtonsKey;
                @ControllerButtonsKey.canceled += instance.OnControllerButtonsKey;
                @ControllerButtonsClassScroll.started += instance.OnControllerButtonsClassScroll;
                @ControllerButtonsClassScroll.performed += instance.OnControllerButtonsClassScroll;
                @ControllerButtonsClassScroll.canceled += instance.OnControllerButtonsClassScroll;
                @ControllerButtonsClassSelect.started += instance.OnControllerButtonsClassSelect;
                @ControllerButtonsClassSelect.performed += instance.OnControllerButtonsClassSelect;
                @ControllerButtonsClassSelect.canceled += instance.OnControllerButtonsClassSelect;
            }
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);
    public interface IPlayerMovementActions
    {
        void OnControllerButtonsShoot(InputAction.CallbackContext context);
        void OnControllerButtonsPotion(InputAction.CallbackContext context);
        void OnControllerButtonsKey(InputAction.CallbackContext context);
        void OnControllerButtonsClassScroll(InputAction.CallbackContext context);
        void OnControllerButtonsClassSelect(InputAction.CallbackContext context);
    }
}
